# Generated by Django 5.2.10 on 2026-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_cost', models.FloatField()),
                ('maintenance_cost', models.FloatField()),
                ('yearly_savings', models.FloatField()),
                ('roi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HybridSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=50)),
                ('solar_power', models.FloatField()),
                ('wind_power', models.FloatField()),
                ('battery_storage', models.FloatField()),
                ('total_output', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('subsidy', models.FloatField()),
                ('tax_benefit', models.FloatField()),
                ('policy_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('irradiance', models.FloatField()),
                ('temperature', models.FloatField()),
                ('energy_generated', models.FloatField()),
            ],
        ),
    ]
